//
// AbilityApiInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AbilityApiInfo: Codable, JSONEncodable, Hashable {

    /** Id of routine. Only regular routines are allowed in abilities. */
    public var routineId: Int?
    /** If set, standalone duration of routine for this employee overrides the default duration */
    public var durationSingleOverride: Int?
    /** If set, combined duration of routine for this employee overrides the default duration */
    public var durationCombinedOverride: Int?
    /** Show the routine on the web portal */
    public var isAvailableOnline: Bool?

    public init(routineId: Int? = nil, durationSingleOverride: Int? = nil, durationCombinedOverride: Int? = nil, isAvailableOnline: Bool? = nil) {
        self.routineId = routineId
        self.durationSingleOverride = durationSingleOverride
        self.durationCombinedOverride = durationCombinedOverride
        self.isAvailableOnline = isAvailableOnline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case routineId
        case durationSingleOverride
        case durationCombinedOverride
        case isAvailableOnline
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(routineId, forKey: .routineId)
        try container.encodeIfPresent(durationSingleOverride, forKey: .durationSingleOverride)
        try container.encodeIfPresent(durationCombinedOverride, forKey: .durationCombinedOverride)
        try container.encodeIfPresent(isAvailableOnline, forKey: .isAvailableOnline)
    }
}

