//
// AppointmentPlanningRequestState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Appointment state - Planned or Reserved. If not specified, Planned is assumed. */
public enum AppointmentPlanningRequestState: Codable, JSONEncodable, Hashable {
    case typeAppointmentState(AppointmentState)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAppointmentState(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AppointmentState.self) {
            self = .typeAppointmentState(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of AppointmentPlanningRequestState"))
        }
    }
}

