//
// AppointmentApiPatchState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AppointmentApiPatchState: Codable, JSONEncodable, Hashable {
    case typePropertyPatchOfAppointmentState(PropertyPatchOfAppointmentState)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typePropertyPatchOfAppointmentState(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(PropertyPatchOfAppointmentState.self) {
            self = .typePropertyPatchOfAppointmentState(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of AppointmentApiPatchState"))
        }
    }
}

