//
// AttachmentContentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum AttachmentContentType: String, Codable, CaseIterable {
    case notDefined = "NotDefined"
    case pdfDocument = "PdfDocument"
    case jpeg = "Jpeg"
    case png = "Png"
    case gif = "Gif"
    case htmlDocument = "HtmlDocument"
    case dicomFile = "DicomFile"
    case xpsDocument = "XpsDocument"
    case wordOpenXml = "WordOpenXml"
    case excelOpenXml = "ExcelOpenXml"
    case calendar = "Calendar"
    case tiff = "Tiff"
    case bmp = "Bmp"
    case avi = "Avi"
    case hl7v2 = "Hl7v2"
    case wav = "Wav"
    case mp3 = "Mp3"
    case ogg = "Ogg"
    case zip = "Zip"
    case webp = "Webp"
    case mp4 = "Mp4"
    case json = "Json"
}
