//
// ComponentApiInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComponentApiInfo: Codable, JSONEncodable, Hashable {

    public var routineId: Int?
    public var quantity: Int?

    public init(routineId: Int? = nil, quantity: Int? = nil) {
        self.routineId = routineId
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case routineId
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(routineId, forKey: .routineId)
        try container.encodeIfPresent(quantity, forKey: .quantity)
    }
}

