//
// CreateAccountRecordApiRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAccountRecordApiRequest: Codable, JSONEncodable, Hashable {

    public var amount: Double
    /** Date and time of transaction. If left empty, current datetime is used */
    public var transactionDateTime: Date?

    public init(amount: Double, transactionDateTime: Date? = nil) {
        self.amount = amount
        self.transactionDateTime = transactionDateTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case transactionDateTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(transactionDateTime, forKey: .transactionDateTime)
    }
}

