//
// DocumentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum DocumentType: String, Codable, CaseIterable {
    case undefined = "Undefined"
    case titlePage = "TitlePage"
    case consultation = "Consultation"
    case diary = "Diary"
    case examinationReport = "ExaminationReport"
    case laboratoryResult = "LaboratoryResult"
    case interventionRecord = "InterventionRecord"
    case prescriptionSheet = "PrescriptionSheet"
    case epicrisis = "Epicrisis"
    case certificate = "Certificate"
    case referral = "Referral"
    case consent = "Consent"
    case contract = "Contract"
    case financial = "Financial"
    case otherNonMedical = "OtherNonMedical"
    case otherMedical = "OtherMedical"
}
