//
// EmployeeApiInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeeApiInfo: Codable, JSONEncodable, Hashable {

    /** Employee id is also a person id */
    public var id: Int?
    public var fullName: String?
    public var specialities: [EntityApiInfo]?
    /** Id of executor resource for this employee */
    public var executorId: Int?
    public var isActive: Bool?

    public init(id: Int? = nil, fullName: String? = nil, specialities: [EntityApiInfo]? = nil, executorId: Int? = nil, isActive: Bool? = nil) {
        self.id = id
        self.fullName = fullName
        self.specialities = specialities
        self.executorId = executorId
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case fullName
        case specialities
        case executorId
        case isActive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(specialities, forKey: .specialities)
        try container.encodeIfPresent(executorId, forKey: .executorId)
        try container.encodeIfPresent(isActive, forKey: .isActive)
    }
}

