//
// EncounterLocationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum EncounterLocationType: String, Codable, CaseIterable {
    case notDefined = "NotDefined"
    case onPremises = "OnPremises"
    case home = "Home"
    case field = "Field"
    case virtual = "Virtual"
    case biomaterialTransfer = "BiomaterialTransfer"
}
