//
// ExecutorUnitTimeslots.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExecutorUnitTimeslots: Codable, JSONEncodable, Hashable {

    public var resourceId: Int?
    public var timeslots: [TimeslotApiInfo]?

    public init(resourceId: Int? = nil, timeslots: [TimeslotApiInfo]? = nil) {
        self.resourceId = resourceId
        self.timeslots = timeslots
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resourceId
        case timeslots
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(resourceId, forKey: .resourceId)
        try container.encodeIfPresent(timeslots, forKey: .timeslots)
    }
}

