//
// MedicalCareType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum MedicalCareType: String, Codable, CaseIterable {
    case notDefined = "NotDefined"
    case outPatient = "OutPatient"
    case inPatient = "InPatient"
    case operations = "Operations"
    case bloodDrawingPoint = "BloodDrawingPoint"
}
