//
// OrderShortApiInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderShortApiInfo: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var number: String?
    public var dateTime: Date?
    public var unitId: Int?

    public init(id: Int? = nil, number: String? = nil, dateTime: Date? = nil, unitId: Int? = nil) {
        self.id = id
        self.number = number
        self.dateTime = dateTime
        self.unitId = unitId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case number
        case dateTime
        case unitId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encodeIfPresent(dateTime, forKey: .dateTime)
        try container.encodeIfPresent(unitId, forKey: .unitId)
    }
}

