//
// PaymentMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum PaymentMethod: String, Codable, CaseIterable {
    case notDefined = "NotDefined"
    case cash = "Cash"
    case bankCard = "BankCard"
    case bankTransfer = "BankTransfer"
    case internet = "Internet"
}
