//
// PersonGender.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum PersonGender: String, Codable, CaseIterable {
    case unspecified = "Unspecified"
    case male = "Male"
    case female = "Female"
}
