//
// PersonDocumentApiAttachContentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Content type. Has priority over file extension. */
public enum PersonDocumentApiAttachContentType: Codable, JSONEncodable, Hashable {
    case typeAttachmentContentType(AttachmentContentType)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAttachmentContentType(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AttachmentContentType.self) {
            self = .typeAttachmentContentType(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PersonDocumentApiAttachContentType"))
        }
    }
}

