//
// PersonChannelApiPatchTypeId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PersonChannelApiPatchTypeId: Codable, JSONEncodable, Hashable {
    case typePropertyPatchOfInteger(PropertyPatchOfInteger)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typePropertyPatchOfInteger(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(PropertyPatchOfInteger.self) {
            self = .typePropertyPatchOfInteger(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PersonChannelApiPatchTypeId"))
        }
    }
}

