//
// PersonDocumentApiAttachDocumentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Specifies target medical card section. Defaults to LaboratoryResult. */
public enum PersonDocumentApiAttachDocumentType: Codable, JSONEncodable, Hashable {
    case typeDocumentType(DocumentType)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeDocumentType(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(DocumentType.self) {
            self = .typeDocumentType(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PersonDocumentApiAttachDocumentType"))
        }
    }
}

