//
// PersonApiPatch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PersonApiPatch: Codable, JSONEncodable, Hashable {

    public var firstName: PersonChannelApiPatchValue?
    public var lastName: PersonChannelApiPatchValue?
    public var patronymicName: PersonChannelApiPatchValue?
    public var dateOfBirth: PersonApiPatchDateOfBirth?
    public var gender: PersonApiPatchGender?

    public init(firstName: PersonChannelApiPatchValue? = nil, lastName: PersonChannelApiPatchValue? = nil, patronymicName: PersonChannelApiPatchValue? = nil, dateOfBirth: PersonApiPatchDateOfBirth? = nil, gender: PersonApiPatchGender? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.patronymicName = patronymicName
        self.dateOfBirth = dateOfBirth
        self.gender = gender
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName
        case lastName
        case patronymicName
        case dateOfBirth
        case gender
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(patronymicName, forKey: .patronymicName)
        try container.encodeIfPresent(dateOfBirth, forKey: .dateOfBirth)
        try container.encodeIfPresent(gender, forKey: .gender)
    }
}

