//
// PersonApiPatchGender.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PersonApiPatchGender: Codable, JSONEncodable, Hashable {
    case typePropertyPatchOfPersonGender(PropertyPatchOfPersonGender)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typePropertyPatchOfPersonGender(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(PropertyPatchOfPersonGender.self) {
            self = .typePropertyPatchOfPersonGender(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of PersonApiPatchGender"))
        }
    }
}

