//
// PlanningResultApiInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlanningResultApiInfo: Codable, JSONEncodable, Hashable {

    public var date: Date?
    public var unit: DocumentApiInfoAuthor?
    public var executor: DocumentApiInfoAuthor?
    public var availableIntervals: [AvailableIntervalApiInfo]?

    public init(date: Date? = nil, unit: DocumentApiInfoAuthor? = nil, executor: DocumentApiInfoAuthor? = nil, availableIntervals: [AvailableIntervalApiInfo]? = nil) {
        self.date = date
        self.unit = unit
        self.executor = executor
        self.availableIntervals = availableIntervals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case unit
        case executor
        case availableIntervals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(unit, forKey: .unit)
        try container.encodeIfPresent(executor, forKey: .executor)
        try container.encodeIfPresent(availableIntervals, forKey: .availableIntervals)
    }
}

