//
// RoutineType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum RoutineType: String, Codable, CaseIterable {
    case notDefined = "NotDefined"
    case regular = "Regular"
    case lab = "Lab"
    case article = "Article"
    case package = "Package"
    case healthPlan = "HealthPlan"
}
