//
// RoutinePromotionApiInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RoutinePromotionApiInfo: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var name: String?
    public var discound: Double?

    public init(id: Int? = nil, name: String? = nil, discound: Double? = nil) {
        self.id = id
        self.name = name
        self.discound = discound
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case discound
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(discound, forKey: .discound)
    }
}

