//
// RoutineAssociationPlanningDataApiInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RoutineAssociationPlanningDataApiInfo: Codable, JSONEncodable, Hashable {

    public var routineId: Int?
    public var plannedFromRoutineId: Int?

    public init(routineId: Int? = nil, plannedFromRoutineId: Int? = nil) {
        self.routineId = routineId
        self.plannedFromRoutineId = plannedFromRoutineId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case routineId
        case plannedFromRoutineId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(routineId, forKey: .routineId)
        try container.encodeIfPresent(plannedFromRoutineId, forKey: .plannedFromRoutineId)
    }
}

