//
// RoutineApiInfoRegularRoutineType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Subtype of Regular (clinic) routine */
public enum RoutineApiInfoRegularRoutineType: Codable, JSONEncodable, Hashable {
    case typeRegularRoutineType(RegularRoutineType)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeRegularRoutineType(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(RegularRoutineType.self) {
            self = .typeRegularRoutineType(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of RoutineApiInfoRegularRoutineType"))
        }
    }
}

