//
// ServiceInAppointmentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceInAppointmentRequest: Codable, JSONEncodable, Hashable {

    /** Routine Id for service */
    public var routineId: Int
    /** Service unit price. Omit this parameter or pass null to get default price from pricelist */
    public var unitPrice: Double?
    /** Service discount, as fraction. 10% discount should be passed as 0.1. Omit this parameter or pass null to get default discount from pricelist */
    public var discount: Double?

    public init(routineId: Int, unitPrice: Double? = nil, discount: Double? = nil) {
        self.routineId = routineId
        self.unitPrice = unitPrice
        self.discount = discount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case routineId
        case unitPrice
        case discount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(routineId, forKey: .routineId)
        try container.encodeIfPresent(unitPrice, forKey: .unitPrice)
        try container.encodeIfPresent(discount, forKey: .discount)
    }
}

