//
// TimeslotApiInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TimeslotApiInfo: Codable, JSONEncodable, Hashable {

    public var date: String?
    public var unitId: Int?
    public var intervalStart: String?
    public var intervalEnd: String?

    public init(date: String? = nil, unitId: Int? = nil, intervalStart: String? = nil, intervalEnd: String? = nil) {
        self.date = date
        self.unitId = unitId
        self.intervalStart = intervalStart
        self.intervalEnd = intervalEnd
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case unitId
        case intervalStart
        case intervalEnd
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(unitId, forKey: .unitId)
        try container.encodeIfPresent(intervalStart, forKey: .intervalStart)
        try container.encodeIfPresent(intervalEnd, forKey: .intervalEnd)
    }
}

