//
// VisitConfirmationState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum VisitConfirmationState: String, Codable, CaseIterable {
    case notDefined = "NotDefined"
    case notConfirmed = "NotConfirmed"
    case messageReminder = "MessageReminder"
    case confirmedByPhone = "ConfirmedByPhone"
    case callFailed = "CallFailed"
    case notNeeded = "NotNeeded"
    case confirmedByOnlineForm = "ConfirmedByOnlineForm"
    case confirmedViaChatBot = "ConfirmedViaChatBot"
}
