//
// HealthCareInstitutionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class HealthCareInstitutionsAPI {

    /**

     - parameter id: (path)  
     - returns: EntityApiInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func healthCareInstitutionsGet(id: Int) async throws -> EntityApiInfo {
        return try await healthCareInstitutionsGetWithRequestBuilder(id: id).execute().body
    }

    /**
     - GET /api/healthCareInstitutions/{id}
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - parameter id: (path)  
     - returns: RequestBuilder<EntityApiInfo> 
     */
    open class func healthCareInstitutionsGetWithRequestBuilder(id: Int) -> RequestBuilder<EntityApiInfo> {
        var localVariablePath = "/api/healthCareInstitutions/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EntityApiInfo>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - returns: [EntityApiInfo]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func healthCareInstitutionsGetAll() async throws -> [EntityApiInfo] {
        return try await healthCareInstitutionsGetAllWithRequestBuilder().execute().body
    }

    /**
     - GET /api/healthCareInstitutions
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - returns: RequestBuilder<[EntityApiInfo]> 
     */
    open class func healthCareInstitutionsGetAllWithRequestBuilder() -> RequestBuilder<[EntityApiInfo]> {
        let localVariablePath = "/api/healthCareInstitutions"
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[EntityApiInfo]>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
