//
// MedRepsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MedRepsAPI {

    /**

     - parameter id: (path)  
     - returns: EntityApiInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func medRepsGet(id: Int) async throws -> EntityApiInfo {
        return try await medRepsGetWithRequestBuilder(id: id).execute().body
    }

    /**
     - GET /api/medReps/{id}
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - parameter id: (path)  
     - returns: RequestBuilder<EntityApiInfo> 
     */
    open class func medRepsGetWithRequestBuilder(id: Int) -> RequestBuilder<EntityApiInfo> {
        var localVariablePath = "/api/medReps/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EntityApiInfo>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - returns: [EntityApiInfo]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func medRepsGetAll() async throws -> [EntityApiInfo] {
        return try await medRepsGetAllWithRequestBuilder().execute().body
    }

    /**
     - GET /api/medReps
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - returns: RequestBuilder<[EntityApiInfo]> 
     */
    open class func medRepsGetAllWithRequestBuilder() -> RequestBuilder<[EntityApiInfo]> {
        let localVariablePath = "/api/medReps"
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[EntityApiInfo]>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
