//
// PaymentsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PaymentsAPI {

    /**
     Create new payment
     
     - parameter createPaymentApiRequest: (body)  
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func paymentsCreatePayment(createPaymentApiRequest: CreatePaymentApiRequest) async throws -> URL {
        return try await paymentsCreatePaymentWithRequestBuilder(createPaymentApiRequest: createPaymentApiRequest).execute().body
    }

    /**
     Create new payment
     - POST /api/payments
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - parameter createPaymentApiRequest: (body)  
     - returns: RequestBuilder<URL> 
     */
    open class func paymentsCreatePaymentWithRequestBuilder(createPaymentApiRequest: CreatePaymentApiRequest) -> RequestBuilder<URL> {
        let localVariablePath = "/api/payments"
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createPaymentApiRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
