//
// PricingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PricingAPI {

    /**

     - returns: [PriceModelApiInfo]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func priceModelsGetPriceModels() async throws -> [PriceModelApiInfo] {
        return try await priceModelsGetPriceModelsWithRequestBuilder().execute().body
    }

    /**
     - GET /api/priceModels
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - returns: RequestBuilder<[PriceModelApiInfo]> 
     */
    open class func priceModelsGetPriceModelsWithRequestBuilder() -> RequestBuilder<[PriceModelApiInfo]> {
        let localVariablePath = "/api/priceModels"
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[PriceModelApiInfo]>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter priceModelId: (path)  
     - returns: [RoutinePriceApiInfo]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func priceModelsGetPriceRules(priceModelId: Int) async throws -> [RoutinePriceApiInfo] {
        return try await priceModelsGetPriceRulesWithRequestBuilder(priceModelId: priceModelId).execute().body
    }

    /**
     - GET /api/priceModels/{priceModelId}/priceRules
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - parameter priceModelId: (path)  
     - returns: RequestBuilder<[RoutinePriceApiInfo]> 
     */
    open class func priceModelsGetPriceRulesWithRequestBuilder(priceModelId: Int) -> RequestBuilder<[RoutinePriceApiInfo]> {
        var localVariablePath = "/api/priceModels/{priceModelId}/priceRules"
        let priceModelIdPreEscape = "\(APIHelper.mapValueToPathItem(priceModelId))"
        let priceModelIdPostEscape = priceModelIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{priceModelId}", with: priceModelIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RoutinePriceApiInfo]>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter priceModelId: (path)  
     - parameter routineId: (path)  
     - returns: RoutinePriceApiInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func priceModelsGetRoutinePrice(priceModelId: Int, routineId: Int) async throws -> RoutinePriceApiInfo {
        return try await priceModelsGetRoutinePriceWithRequestBuilder(priceModelId: priceModelId, routineId: routineId).execute().body
    }

    /**
     - GET /api/priceModels/{priceModelId}/routines/{routineId}
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - parameter priceModelId: (path)  
     - parameter routineId: (path)  
     - returns: RequestBuilder<RoutinePriceApiInfo> 
     */
    open class func priceModelsGetRoutinePriceWithRequestBuilder(priceModelId: Int, routineId: Int) -> RequestBuilder<RoutinePriceApiInfo> {
        var localVariablePath = "/api/priceModels/{priceModelId}/routines/{routineId}"
        let priceModelIdPreEscape = "\(APIHelper.mapValueToPathItem(priceModelId))"
        let priceModelIdPostEscape = priceModelIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{priceModelId}", with: priceModelIdPostEscape, options: .literal, range: nil)
        let routineIdPreEscape = "\(APIHelper.mapValueToPathItem(routineId))"
        let routineIdPostEscape = routineIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{routineId}", with: routineIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoutinePriceApiInfo>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
