//
// PromotionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PromotionsAPI {

    /**
     Get all active promotions
     
     - returns: [EntityApiInfo]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func promotionGetAll() async throws -> [EntityApiInfo] {
        return try await promotionGetAllWithRequestBuilder().execute().body
    }

    /**
     Get all active promotions
     - GET /api/promotions
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - returns: RequestBuilder<[EntityApiInfo]> 
     */
    open class func promotionGetAllWithRequestBuilder() -> RequestBuilder<[EntityApiInfo]> {
        let localVariablePath = "/api/promotions"
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[EntityApiInfo]>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get promotion details
     
     - parameter promotionId: (path)  
     - returns: PromotionApiInfo
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func promotionGetPromotion(promotionId: Int) async throws -> PromotionApiInfo {
        return try await promotionGetPromotionWithRequestBuilder(promotionId: promotionId).execute().body
    }

    /**
     Get promotion details
     - GET /api/promotions/{promotionId}
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - parameter promotionId: (path)  
     - returns: RequestBuilder<PromotionApiInfo> 
     */
    open class func promotionGetPromotionWithRequestBuilder(promotionId: Int) -> RequestBuilder<PromotionApiInfo> {
        var localVariablePath = "/api/promotions/{promotionId}"
        let promotionIdPreEscape = "\(APIHelper.mapValueToPathItem(promotionId))"
        let promotionIdPostEscape = promotionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{promotionId}", with: promotionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PromotionApiInfo>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get possible promotions for routine
     
     - parameter routineId: (path)  
     - returns: [RoutinePromotionApiInfo]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func promotionGetRoutinePromotions(routineId: Int) async throws -> [RoutinePromotionApiInfo] {
        return try await promotionGetRoutinePromotionsWithRequestBuilder(routineId: routineId).execute().body
    }

    /**
     Get possible promotions for routine
     - GET /api/routines/{routineId}/promotions
     - API Key:
       - type: apiKey Api-Key (HEADER)
       - name: Api-Key
     - parameter routineId: (path)  
     - returns: RequestBuilder<[RoutinePromotionApiInfo]> 
     */
    open class func promotionGetRoutinePromotionsWithRequestBuilder(routineId: Int) -> RequestBuilder<[RoutinePromotionApiInfo]> {
        var localVariablePath = "/api/routines/{routineId}/promotions"
        let routineIdPreEscape = "\(APIHelper.mapValueToPathItem(routineId))"
        let routineIdPostEscape = routineIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{routineId}", with: routineIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = APIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RoutinePromotionApiInfo]>.Type = APIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
